-- Auto-generated by scripts/backfill-album-art.mjs
-- URLs verified via Spotify Search API — safe to re-run.

UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273cdb645498cd3d8a2db4d05e1' WHERE spotify_id = 'seed_bm_01'; -- Alright
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273daec894c14c0ca42d76eeb32' WHERE spotify_id = 'seed_bm_02'; -- SICKO MODE
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b27330a635de2bb0caa4e26f6abb' WHERE spotify_id = 'seed_bm_03'; -- EARFQUAKE
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b2738752a7355996e64709247c53' WHERE spotify_id = 'seed_bm_04'; -- Goosebumps
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273d28d2ebdedb220e479743797' WHERE spotify_id = 'seed_bm_05'; -- Money Trees
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b27349d694203245f241a1bcaa72' WHERE spotify_id = 'seed_mg_01'; -- Tití Me Preguntó
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273005ee342f4eef2cc6e8436ab' WHERE spotify_id = 'seed_mg_02'; -- La Noche de Anoche
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273b115d8632e69edce1a1da7d8' WHERE spotify_id = 'seed_mg_03'; -- Malamente
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273896ffcd42561c44fea2bae7b' WHERE spotify_id = 'seed_mg_04'; -- Con Calma
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273079fb6c5ba37dc11d66ce1e2' WHERE spotify_id = 'seed_mg_05'; -- Hawái
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273c5649add07ed3720be9d5526' WHERE spotify_id = 'seed_ws_01'; -- Ivy
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273bc18bdade69ec5ef0bb25b17' WHERE spotify_id = 'seed_ws_02'; -- Good Days
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b2734b6b1547455bbecb9f6bba64' WHERE spotify_id = 'seed_ws_03'; -- Holocene
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b27359a428dc7ef8e0c12b0fe18a' WHERE spotify_id = 'seed_ws_04'; -- Novacane
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b27306d56b057cce5797538a16d5' WHERE spotify_id = 'seed_ws_05'; -- Broken Clocks
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273c6e0948bbb0681ff29cdbae8' WHERE spotify_id = 'seed_lf_01'; -- No Role Modelz
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273b5e18a80757ba2f787213d21' WHERE spotify_id = 'seed_lf_02'; -- On & On
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273c6e0948bbb0681ff29cdbae8' WHERE spotify_id = 'seed_lf_03'; -- Love Yourz
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273b5e18a80757ba2f787213d21' WHERE spotify_id = 'seed_lf_04'; -- Next Lifetime
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b273cf0f0affd0138a7442f13706' WHERE spotify_id = 'seed_lf_05'; -- Kevin's Heart
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b2738863bc11d2aa12b54f5aeb36' WHERE spotify_id = 'seed_dp_01'; -- Blinding Lights
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b2734aa538a481e67131c214135a' WHERE spotify_id = 'seed_dp_02'; -- Levitating
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b27395f754318336a07e85ec59bc' WHERE spotify_id = 'seed_dp_03'; -- cardigan
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b2738863bc11d2aa12b54f5aeb36' WHERE spotify_id = 'seed_dp_04'; -- Save Your Tears
UPDATE public.songs SET album_art_url = 'https://i.scdn.co/image/ab67616d0000b2738bd7c90e2316fc02b6416b35' WHERE spotify_id = 'seed_dp_05'; -- New Rules
